import man_tshirt_1 from "./images/Marvel-Men-T-Shirt-1.jpeg"
import man_tshirt_2 from "./images/marvel-men-tshirt-2.jpg"
import man_tshirt_3 from "./images/marvel-men-tshirt-3.jpg"
// import man_tshirt_4 from "./images/marvel-men-tshirt-4.jpeg"
import man_tshirt_5 from "./images/marvel-men-tshirt-5.jpeg"
import hoodie_1 from "./images/marvel-men-hoodie-1.jpeg"
import hoodie_2 from "./images/marvel-men-hoodie-2.jpeg"
import hoodie_3 from "./images/marvel-men-hoodie-3.jpg"
import man_jacket_1 from "./images/marvel-men-jacket-1.jpg"
import man_jacket_2 from "./images/marvel-men-jacket-2.jpg"
import woman_tshirt_1 from "./images/marvel-women-tshirt-1.jpeg"
import woman_tshirt_2 from "./images/marvel-woman-tshirt-2.jpg"
import woman_tshirt_3 from "./images/marvel-woman-tshirt-3.jpg"

export { man_tshirt_1, man_tshirt_2, man_tshirt_3, man_tshirt_5, hoodie_1, hoodie_2, hoodie_3, man_jacket_1, man_jacket_2, woman_tshirt_1, woman_tshirt_2, woman_tshirt_3 }